### PR TITLE
Fix brod:create_topics typespecs

### PR DESCRIPTION
**Pull request by DianaOlympos**
I updated the typespec to reflect what it does today. I am not sure it should be the behaviour and i did not update the documentation as i do not fully understand why it does not always return the struct as expected.

### CODE REVIEW

**Comment by Coffei** [comment]
This problem seems to concern `delete_topics` APIs as well. Could you also fix that?

**Comment by DianaOlympos** [comment]
Done. Tbh i think it would be better if we understood where it come from because i am not sure we can really receive a `{ok, kpro:struct()}` anymore. but not 100% sure.

**Comment by k32** [comment]
Hi @DianaOlympos,

Thanks for the PR!

**Review by k32 — APPROVED** [review]
New specs look more correct when I compare them with the typer output.

**Pull request merged**
