### PR TITLE
Remove snappyer from default dependency

### PR DESCRIPTION
**Pull request by belltoy**
The snappy support is optional and configurable after kafka_protocol 4.0 in https://github.com/kafka4beam/brod/pull/459, so it should not be a default dependency. Besides, making it default will prevent users from excluding it.

This is a breaking change. Users using producers and/or consumers with compression enabled must explicitly add a compression application/module.

### CODE REVIEW

**Comment by belltoy** [comment]
BTW, why is there a rebar.lock file in this repo?

**Comment by zmstone** [comment]
Hi @belltoy 
Thank you for the PR. and sorry for the embarrassingly late respond. 
Now it needs a rebase.

**Comment by belltoy** [comment]
Rebased onto the latest master branch.

Changes:

- Remove `snappyer` dependency but keep it for `brod-cli` and `test` profiles.
- Fix `[docopt-erl](https://github.com/zmstone/docopt-erl)` dependency

**Comment by zmstone** [comment]
Thank you @belltoy  will release a major version soon.

**Comment by belltoy** [comment]
Thanks, Stone.

**Comment by kivra-pauoli** [comment]
+1 for this. I'm trying to compile on OTP 27 and `snappyer` isn't happy. Also: https://github.com/zmstone/snappyer/issues/10. It'd be a good compromise to allow not using `snappyer` (thus not affecting CI) while it doesn't get OTP 27 support.

**Review by yordis — APPROVED** [review]

**Review by zmstone — APPROVED** [review]

**Comment by zmstone** [comment]
released 4.0.0

**Pull request merged**
