### PR TITLE
SASL GSSAPI support

### PR DESCRIPTION
**Pull request by ElMaxo**
I have implemented experimental SASL GSSAPI auth mechanism support. To enable this - add `{sasl, {kerberos, Keytab, Principal}}` to client config. Please, let me know if you found any bugs. I want to add automatic ticket renew in future

### CODE REVIEW

**Comment by id** [comment]
@ElMaxo nice, thanks! We'll take a look.

**Comment by ElMaxo** [comment]
To build sasl_auth.c libsasl2 (cyrus sasl) should be installed with headers

**Comment by zmstone** [comment]
@ElMaxo Thank you for your contribution.
This adds more compile time dependency for the users who don't need this new auth support.
We'd like to have this supported in a more flexible way:
1. Put the nif code to a separate Erlang project.
2. Add a `{auth_callback_module, ModuleName}` client config (and maybe introduce a `-behaviour` module to define the callback specs)
3. Update README with info about how to enable SASL GSSAPI auth.

**Comment by ElMaxo** [comment]
@zmstone ok, I'll do it in some days and write you back

**Comment by zmstone** [comment]
Covered by #210

**Pull request closed without merging**
