### PR TITLE
kafka4beam mergeback

### PR DESCRIPTION
**Pull request by zmstone**
before we can automate it

### CODE REVIEW

**Comment by zmstone** [comment]
come on it's apache 2

**Comment by robertoaloi** [comment]
@zmstone The CLA was added as part of a standard process. I am talking to the responsible persons to see if we can relax that requirement for the Kafka related repositories.

**Comment by zmstone** [comment]
> @zmstone The CLA was added as part of a standard process. I am talking to the responsible persons to see if we can relax that requirement for the Kafka related repositories.

Nice.

**Comment by zmstone** [comment]
worst case scenario someone can maybe use admin privilege to merge ?
I can only speak for myself, maybe I can sign,
but https://github.com/kafka4beam will be open for contributions from others without Klarna's involvement.

**Pull request merged**
