### PR TITLE
Close connection on fetch_committed_offsets/3

### PR DESCRIPTION
**Pull request by ates**
After request the connection should be closed

### CODE REVIEW

**Comment by ates** [comment]
Any update?

**Comment by mikpe** [comment]
What problem does this solve? I would assume that not eagerly closing the connection would allow us to reuse it soon afterwards. Does that reuse not happen?

**Comment by ates** [comment]
Yes, it do not reuse the connection and for each call it spawn new process

```
1> brod:start_client([{"localhost", 9092}], c1, []).
ok
2> process_info(self(), [links]).                    
[{links,[<0.522.0>]}]
3> [brod:fetch_committed_offsets(c1, <<"some-group">>) || _ <- lists:seq(1, 10)].
[{ok,[]},
 {ok,[]},
 {ok,[]},
 {ok,[]},
 {ok,[]},
 {ok,[]},
 {ok,[]},
 {ok,[]},
 {ok,[]},
 {ok,[]}]
4> process_info(self(), [links]).      
[{links,[<0.967.0>,<0.971.0>,<0.975.0>,<0.979.0>,<0.981.0>,
         <0.977.0>,<0.973.0>,<0.969.0>,<0.963.0>,<0.965.0>,
         <0.522.0>]}]
```

**Review by zmstone — APPROVED** [review]

**Comment by zmstone** [comment]
thank you for the PR
and sorry for the delay

**Comment by zmstone** [comment]
included in 3.15.3, published to hex

**Pull request merged**
