### PR TITLE
Fix behavior during crashing of the group coordinator

### PR DESCRIPTION
**Pull request by k32**
Fixes https://github.com/klarna/brod/issues/433

### CODE REVIEW

**Review by zmstone — APPROVED** [review]

**Comment by k32** [comment]
Hi @epsylonix ,

This is the partial fix to the problem that you encountered. Thanks for the remarks on the other code review. I took them into account.
Please note that this PR doesn't fix the other problem that you mentioned, about lost commits during shutdown. Fixing it requires some rework of the behavior, which I am planning to do.

**Review by zmstone — APPROVED** [review]

**Comment by epsylonix** [comment]
Great, thank you very much! 

Regarding the dropped offset acks issue - maybe it could be resolved in a similar way `brod_group_coordinator` does it [here](https://github.com/kafka4beam/brod/blob/master/src/brod_group_coordinator.erl#L497)? 
By the way, `brod_group_subscriber_v2` should probably receive all acks and commit those offsets when partitions are revoked (and before the new ones are assigned), because it seems that otherwise those acks could be later ignored and those messages could be read again by new workers that would receive those partitions after the rebalance.

**Comment by k32** [comment]
Yes, that's the way it should be done. Although technically I would prefer to migrate to `gen_statem` behavior instead of sending control messages to the process.

**Comment by epsylonix** [comment]
Maybe there is even an easier way to solve both of those problems - `brod_group_subscriber_v2` passes a commit function to the worker, so maybe of just casting the ack to itself from that function it could be possible to do everything `brod_group_subscriber_v2:handle_cast({commit_offset, ...`  does right away from that commit fun? As far as I can see, `brod_group_subscriber_v2` is not changed in there, `Coordinator` pid doesn't ever change, the `GenerationId` could change but if I'm not sure a worker started with old generation id should be allowed to commit any offsets (or process any messages :) ) because otherwise it would defeat the purpose of `GenerationId`. If this could be done then it seems like `brod_group_coordinator` would take care of those acks without any modifications.

I'm not sure if this wouldn't result in some sort of a deadlock though, I'm not very familiar with the code.

**Comment by k32** [comment]
Yes, I was also thinking that proxying the commit messages through the subscriber process probably could be avoided.

**Comment by k32** [comment]
P.S. I think I remember now why this proxying was implemented. The reason is not strictly related to any deadlocks, rather to the initialization process. The function for performing asynchronous commit is implemented as a closure that, among other things, has to ask the consumer process for more data. In order to do that, it needs to know its own pid. So the fix would be to introduce a two-stage initialization process. Thankfully, now I realize that should not complicate the startup of the worker process, and it can be done via pure code.

**Review by epsylonix — COMMENTED** [review]
Hi @k32, could you please look into these probable issues?

**Pull request merged**
