### PR TITLE
brod_producer_buffer: use a queue for pending and buffer

### PR DESCRIPTION
**Pull request by eriklee**
This switches the brod_producer_buffer pending and buffer state elements to be queues instead of lists. This seems to have improved performance with heavy load a fair bit.

Unfortunately it does make the code a fair bit uglier, but I tried to avoid it as much as I could with the EMPTY_QUEUE macro.

### CODE REVIEW

**Comment by zmstone** [comment]
I think you have missed some lines. e.g. line 278.
also, run ct with: `make ct-brod_producer_buffer`

**Comment by zmstone** [comment]
@id  do you think it's time to stop supporting pre-17 OTP?
otherwise we'll have to add some compilation switches to support queue() or queue:queue() type specs (both for erlang.mk and rebar).

**Comment by id** [comment]
@zmstone yep, I think we should drop it.

**Comment by eriklee** [comment]
Ah, so I have. Apparently my brokers never fail :)

Now passes the tests. I'm having a hard time getting `make test-env t` to work (lots of problems with timeouts and sock down). ~~Is this expected?~~ I see they are from the official one. I'm still getting non-0 error codes though...

**Comment by zmstone** [comment]
Good work!

Regarding tests.
First, there are intended failures in the SUITEs (in case you are referring to those kind of timeouts and sock down).

We have seen unstable tests in travis, sometimes I have to rerun the tests, but mostly due test-env failure.

In local setup, you may run `make test-env` first, then repeat `make t`.
I've noticed consumer group failures in the initial run, but usually get back to normal in the second run.

If you notice any test case fail repeatedly, please send an issue to us.

**Review by zmstone — APPROVED** [review]

**Review by id — APPROVED** [review]

**Comment by zmstone** [comment]
@eriklee Thanks a lot, again! :)
Please report an issue for your non-0 error codes in `make t` if it's not a problem in your local setup.

**Comment by eriklee** [comment]
Found the problem, there was a bad version of kafka_protocol in my deps. Everything seems to be working now. :)

**Pull request merged**
