### PR TITLE
Update to kpro 4

### PR DESCRIPTION
**Pull request by tpitale**
Update to kpro 4

* fix updates to field names
* update to kpro 4 includes fixes for delete_topics field names

`make ut` is passing

`make t` is passing, except for any use of `snappyer` `compress`. Investigating, but any assistance would be appreciated.

Related to #69.

### CODE REVIEW

**Comment by tpitale** [comment]
cc @zmstone

**Comment by tpitale** [comment]
Also related: https://github.com/kafka4beam/brod/discussions/454

**Comment by zmstone** [comment]
sorry for the late review @tpitale
could you rebase on latest master? we have fixed the CI there

**Comment by zmstone** [comment]
Please help to update the TODO list in README.md

**Comment by tpitale** [comment]
@zmstone

1. Should I remove the line about kafka protocol from the todos?
2. What version should be next in the changelog? 3.16.0 maybe?

**Comment by zmstone** [comment]
> @zmstone
> 
> 1. Should I remove the line about kafka protocol from the todos

yes
> 2. What version should be next in the changelog? 3.16.0 maybe?

yes


thank you.

**Comment by tpitale** [comment]
@zmstone Made those changes. What do you think I should do with the snappyer errors?

**Comment by zmstone** [comment]
> @zmstone Made those changes. What do you think I should do with the snappyer errors?

sorry for the delay.
I pushed a commit to your branch.

**Review by zmstone — APPROVED** [review]

**Comment by zmstone** [comment]
thank you @tpitale 
3.16.0 has been tagged and published to hex.pm.

**Comment by tpitale** [comment]
Thank you!

**Pull request merged**
