### PR TITLE
(#381): fix potential live upgrade problem in brod_sup

### PR DESCRIPTION
**Pull request by tothlac**

### CODE REVIEW

**Review by mikpe — CHANGES_REQUESTED** [review]
No, this would lead to inconsistencies, the code must either use plain supervisor, or supervisor3, never mix the two.  There are two questions that need answering:
1. Why is brod using supervisor3?  I wasn't involved with brod's initial development, and the git log doesn't really say.  @zmstone @id can either of you shed some light on this?
2. Why doesn't supervisor3 work for the live upgrade case you reported?  That would possibly be a bug in supervisor3, not in brod.

**Comment by zmstone** [comment]
supervisor3 is a copy of supervisor2 from rabbitmq
in fact the repo is a fork of rabbitmq but with only supervisor2 code kept and renamed to supervisor3 to avoid module clashing.
Why we needed supervisor3 was because we like the delayed restart feature.

from the issue description, it seems to me that the tool failed to recognise supervisor3 as a legit supervisor module.

**Comment by mikpe** [comment]
Thanks @zmstone and @robertoaloi, I kind of suspected supervisor3 had gone stale and missed some newer glue with OTP, though I didn't suspect it was _that_ raw and low-level.  I'll take a look at updating supervisor3 unless someone else beats me to it.

**Comment by robertoaloi** [comment]
Hi @mikpe . There is a PR with a patch from @tothlac that fixes the direct issue. See https://github.com/klarna/supervisor3/pull/22

In there, I'm proposing some options for the long-term plans for supervisor3. Please let me know what do you think there.

**Pull request closed without merging**
