### PR TITLE
Terminate group_subscriber_v2 workers on coordinator crash

### LINKED ISSUE #433: brod_group_subscriber_v2 doesn't always stop consumers for partitions on termination
Hello!

I've encountered a problem when multiple instances of a service started consuming data from the same partitions.

As far as I can understand, what happened was `brod_group_coordinator` crashed and that in turn crashed `brod_group_subscriber_v2`.  Since `brod_group_subscriber_v2` `unlink`s its workers, the workers continued to consume data using old assignments. I'm not sure if that would work given that they were started with a different generation, but here is what I could get from logs and from remote connection to the service:

new assignments were received, `brod_group_subscriber_v2` started workers for every partition, but then `brod_group_coordinator` crashed 
```
2021-02-17 01:47:54.161 [info] pid=<0.16781.4032>  Group member (some-group,coor=#PID<0.16781.4032>,cb=#PID<0.16940.4032>,generation=22):
assignments received:
  some-topic:
    partition=0 begin_offset=109503
    partition=4 begin_offset=20271
    partition=8 begin_offset=35433
2021-02-17 01:47:54.162 [info] pid=<0.22956.4032>  Starting group_subscriber_worker: %{commit_fun: #Function<3.129769404/1 in :brod_group_subscriber_v2.maybe_start_worker/6>, group_id: "some-group", partition: 0, topic: "some-topic"}
Offset: 109503
Pid: #PID<0.22956.4032>

2021-02-17 01:47:54.162 [info] pid=<0.16781.4032>  Group member (some-group,coor=#PID<0.16781.4032>,cb=#PID<0.16940.4032>,generation=22):
Leaving group, reason: :hb_timeout

2021-02-17 01:47:54.162 [info] pid=<0.24237.4032>  Starting group_subscriber_worker: %{commit_fun: #Function<3.129769404/1 in :brod_group_subscriber_v2.maybe_start_worker/6>, group_id: "some-group", partition: 4, topic: "some-topic"}
Offset: 20271
Pid: #PID<0.24237.4032>

2021-02-17 01:47:54.163 [info] pid=<0.24692.4032>  Starting group_subscriber_worker: %{commit_fun: #Function<3.129769404/1 in :brod_group_subscriber_v2.maybe_start_worker/6>, group_id: "some-group", partition: 8, topic: "some-topic"}
Offset: 35433
Pid: #PID<0.24692.4032>

2021-02-17 01:47:54.163 [info] pid=<0.2230.0>  Fetch error some-topic-8: :not_leader_for_partition
** (stop) :hb_timeout
Last message: :lo_cmd_send_heartbeat
```

then everything got restarted and new assignments for different partitions were received, but workers for old partitions were not stopped:

```
2021-02-17 01:47:59.166 [info] pid=<0.22810.4032>  Group member (some-group,coor=#PID<0.22810.4032>,cb=#PID<0.24452.4032>,generation=23):
elected=false
2021-02-17 01:47:59.169 [info] pid=<0.22810.4032>  Group member (some-group,coor=#PID<0.22810.4032>,cb=#PID<0.24452.4032>,generation=23):
assignments received:
  some-topic:
    partition=3 begin_offset=17157
    partition=7 begin_offset=27245
    partition=11 begin_offset=31523
2021-02-17 01:47:59.170 [info] pid=<0.24780.4032>  Starting group_subscriber_worker: %{commit_fun: #Function<3.129769404/1 in :brod_group_subscriber_v2.maybe_start_worker/6>, group_id: "some-group", partition: 3, topic: "some-topic"}
Offset: 17157
Pid: #PID<0.24780.4032>

2021-02-17 01:47:59.171 [info] pid=<0.23822.4032>  Starting group_subscriber_worker: %{commit_fun: #Function<3.129769404/1 in :brod_group_subscriber_v2.maybe_start_worker/6>, group_id: "some-group", partition: 7, topic: "some-topic"}
Offset: 27245
Pid: #PID<0.23822.4032>

2021-02-17 01:47:59.172 [info] pid=<0.24652.4032>  Starting group_subscriber_worker: %{commit_fun: #Function<3.129769404/1 in :brod_group_subscriber_v2.maybe_start_worker/6>, group_id: "some-group", partition: 11, topic: "some-topic"}
Offset: 31523
Pid: #PID<0.24652.4032>
```

for example I could see a live topic subscriber for partition 8 that was not supposed to be active:
```
Process.info(:erlang.list_to_pid('<0.24692.4032>'))            
[
  current_function: {:gen_server, :loop, 7},
  initial_call: {:proc_lib, :init_p, 5},
  status: :waiting,
  message_queue_len: 0,
  links: [],
  dictionary: [
    "$initial_call": {:brod_topic_subscriber, :init, 1},
    "$ancestors": [#PID<0.16940.4032>, #PID<0.2208.0>, App.Supervisor,
     #PID<0.1959.0>]
  ],
  trap_exit: false,
  error_handler: :error_handler,
  priority: :normal,
  group_leader: #PID<0.1958.0>,
  total_heap_size: 13544,
  heap_size: 6772,
  stack_size: 10,
  reductions: 210446362,
  garbage_collection: [
    max_heap_size: %{error_logger: true, kill: true, size: 0},
    min_bin_vheap_size: 46422,
    min_heap_size: 233,
    fullsweep_after: 65535,
    minor_gcs: 43
  ],
  suspending: []
]

{:state, :"kafka_consumer_client_some-group",
 #Reference<0.3387090685.283901953.155268>, some-topic",
 [
   {:consumer, 8, #PID<0.2230.0>, #Reference<0.3387090684.3205758978.12960>,
    26599544, 26599544}
 ], :brod_group_subscriber_worker,
 {:state,
  %{
    begin_offset: 26575433,
    cb_config: nil,
    cb_module: App.Consumer,
    commit_fun: #Function<3.129769404/1 in :brod_group_subscriber_v2.maybe_start_worker/6>,
    group_id: "some-group",
    partition: 8,
    topic: some-topic"
  }, App.Consumer, nil,
  #Function<3.129769404/1 in :brod_group_subscriber_v2.maybe_start_worker/6>},
 :message_set}
```
the first ancestor of this process was `<0.16940.4032>`, the `brod_group_subscriber_v2`, and it was not running at the moment:
```
:erlang.is_process_alive(:erlang.list_to_pid('<0.16940.4032>'))
false
```

### PR DESCRIPTION
**Pull request by k32**
Fixes #433

### CODE REVIEW

**Comment by k32** [comment]
It turns out that Klarna org added CLA that requires contributors to doxx themself among other things. Sorry, I ain't signing it.

**Comment by epsylonix** [comment]
well, that's unfortunate. @zmstone, is there a way to resolve this issue? As far as I can understand, @k32 was maintaining this module, will it be unmaintained now? This is a critical bug that could lead up to multiple subscriptions to the same partition and uncommitted offsets, it would be great if you could merge this fix after all. 

@k32 in the hopes that this situation will be resolved after all, could you please answer a couple of questions? I'm not very familiar with the code but looking at the fix I have these concerns:
- it seems that `brod_group_coordinator` started from `brod_group_subscriber_v2` is not stopped in any case. This was the case even before so it could have been left running if someone had terminated the `brod_group_subscriber_v2` process, but now it could happen also on  `brod_group_subscriber_v2` crash. Shouldn't it be stopped in `brod_group_subscriber_v2:terminate` too?
- I believe it is still possible to leave both `brod_group_coordinator` and topic subscriber workers after `brod_group_subscriber_v2` termination if for example it is shut down by a supervisor. Since `brod_group_subscriber_v2` is not trapping exits, `terminate` will not be called on `shutdown` exit. But since every process started from `brod_group_subscriber_v2` is also unlinked wouldn't it be reasonable to simply trap exits instead to solve both of these problems?
- when `brod_group_subscriber_worker` is terminated from `brod_group_subscriber_v2` it might be still handling messages and it seems to be possible that it will try to commit offsets (essentially calling `brod_group_subscriber_v2:commit`) before termination. But `brod_group_subscriber_v2:commit` is done through `gen_server:cast` to the `brod_group_subscriber_v2` process which is already terminating and would not be able to process this commit offsets message. Could this leave final offsets uncommited?

**Comment by k32** [comment]
We are in search of the solution.

**Comment by k32** [comment]
> it seems that `brod_group_coordinator` started from `brod_group_subscriber_v2` is not stopped in any case.

Yes, it may be the case, since the proposed patch unlinked the coordinator process. A better solution would be to change group_subscriber_v2 to trap exits (as you suggested) and having it linked to both workers processes and the coordinator.

> But brod_group_subscriber_v2:commit is done through gen_server:cast to the brod_group_subscriber_v2 process which is already terminating and would not be able to process this commit offsets message. Could this leave final offsets uncommited?

Commits that were received during the shutdown phase may be lost indeed, since "graceful" shutdown is happening in the terminate callback. It was not critical during the initial design of the behavior, since our consumers were idempotent and replaying the messages wouldn't do harm, but ideally that could be handled in a better way.

**Pull request closed without merging**
